name: Release Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Derive version
        run: |
          TAG_NAME="${GITHUB_REF_NAME}"
          VERSION="${TAG_NAME#v}"
          echo "TAG_NAME=${TAG_NAME}" >> "$GITHUB_ENV"
          echo "PACKAGE_VERSION=${VERSION}" >> "$GITHUB_ENV"

      - name: Build distribution
        run: bash script/make_dist.sh "$TAG_NAME"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/lang-ship-native-${{ env.PACKAGE_VERSION }}.zip
            dist/lang-ship-native-${{ env.PACKAGE_VERSION }}.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
